# ==============================================================================
# CẤU HÌNH KẾT NỐI DATABASE MYSQL TRÊN XAMPP
# ==============================================================================
# Driver JDBC
db.driver=com.mysql.cj.jdbc.Driver

# Chuỗi kết nối JDBC (Mặc định XAMPP cổng 3306, CSDL: web_app_group_db)
# Kèm các cờ useSSL=false và allowPublicKeyRetrieval=true để tránh lỗi bảo mật MySQL 8
db.url=jdbc:mysql://localhost:3306/web_app_group_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true

# Tài khoản mặc định của MySQL trên XAMPP
db.user=root

# Mật khẩu mặc định của MySQL trên XAMPP là để trống (nếu bạn có đặt pass thì điền vào đây)
db.password=
